aliases: []
creation_timestamp: 1765129332636
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1765129332636
metrics: null
model_id: m-d7a7e016ea6f4f9ab1ceeb140ecf9ba3
name: sentiment-logreg-tfidf
params: null
run_id: 6e61414555d84f4c90a29ff40282d6d0
run_link: null
source: models:/m-d7a7e016ea6f4f9ab1ceeb140ecf9ba3
status: READY
status_message: null
storage_location: file:C:/Users/jorda/OneDrive/Documentos/Mentoria_ML_ITAU/MLOPSProjetoFinal/mlruns/139583362799314795/models/m-d7a7e016ea6f4f9ab1ceeb140ecf9ba3/artifacts
user_id: null
version: 1
