artifact_location: file:C:/Users/jorda/OneDrive/Documentos/Mentoria_ML_ITAU/MLOPSProjetoFinal/mlruns/0
creation_time: 1765129304362
experiment_id: '0'
last_update_time: 1765129304362
lifecycle_stage: active
name: Default
